
let ARTICLES=[],QA=[],SECTIONS=[];
const STOP=new Set(["the","and","for","with","from","that","this","what","when","where","which","how","can","should","does","into","under","about","your","you","are","was","will","have","has","had","not","any","all","who","why","may","than","then","their","them","they","its","our","out","use","used","using","to","of","in","on","a","an","or","is","be","by","as","at","if","it"]);
function toks(s){return String(s||"").toLowerCase().replace(/[^a-z0-9]+/g," ").split(/\s+/).filter(x=>x.length>1&&!STOP.has(x))}
function score(q,t){let qs=toks(q),ts=new Set(toks(t));let n=0;for(const x of qs)if(ts.has(x))n++;return n}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
async function loadData(){[ARTICLES,QA,SECTIONS]=await Promise.all([fetch("/data/articles.json").then(r=>r.json()),fetch("/data/questions.json").then(r=>r.json()),fetch("/data/sections.json").then(r=>r.json())])}
function articleResults(q){return ARTICLES.map(a=>({...a,_s:score(q,a.title+" "+a.intro+" "+a.category)})).sort((a,b)=>b._s-a._s).slice(0,20).filter(a=>!q||a._s>0)}
function qaResults(q){return QA.map(a=>({...a,_s:score(q,a.question+" "+a.answer)})).sort((a,b)=>b._s-a._s).slice(0,20).filter(a=>!q||a._s>0)}
function renderArticles(items,target="articleResults"){document.getElementById(target).innerHTML=items.map(a=>`<div class="result"><div class="chip">${esc(a.category)}</div><h3><a href="/articles/${esc(a.slug)}.html">${esc(a.title)}</a></h3><p>${esc(a.intro)}</p><p style="margin-top:10px"><a class="btn btn-blue" href="/articles/${esc(a.slug)}.html">Read article →</a></p></div>`).join("")||'<div class="result"><p>No matching article found. Try a broader topic.</p></div>'}
function renderQA(items){document.getElementById("qaResults").innerHTML=items.map(a=>`<div class="result"><h3>${esc(a.question)}</h3><p>${esc(a.answer).slice(0,700)}…</p></div>`).join("")||'<div class="result"><p>No matching question found.</p></div>'}
function searchArticles(){const q=document.getElementById("articleSearch").value.trim();if(q&&typeof gtag==="function")gtag("event","search",{search_term:q});renderArticles(articleResults(q))}
function searchQA(){const q=document.getElementById("qaSearch").value.trim();if(q&&typeof gtag==="function")gtag("event","search",{search_term:q});renderQA(qaResults(q))}
function renderSections(){document.getElementById("sectionResults").innerHTML=SECTIONS.map(s=>`<a class="section-card" href="/gst-act/section-${esc(s.number)}.html"><strong>Section ${esc(s.number)}</strong><div>${esc(s.title)}</div></a>`).join("")}
function localAI(q){let ar=articleResults(q),qr=qaResults(q);if(qr[0]&&qr[0]._s>=2)return {answer:qr[0].answer,article:ARTICLES.find(a=>a.id===qr[0].article_id)};if(ar[0]&&ar[0]._s>=2)return {answer:ar[0].intro+" "+ar[0].legal+" "+ar[0].example,article:ar[0]};return null}
async function askGST(){const q=document.getElementById("gstQuestion").value.trim(),status=document.getElementById("aiStatus"),out=document.getElementById("aiAnswer");if(!q){status.textContent="Please type your question.";return}if(typeof gtag==="function")gtag("event","ask_gst_ai",{question_length:q.length});status.textContent="Searching the GST knowledge library…";out.innerHTML="";let r=localAI(q);if(r){out.innerHTML=`<div class="answer">${esc(r.answer)}${r.article?`<p><a class="btn btn-blue" href="/articles/${esc(r.article.slug)}.html">Read the full article →</a></p>`:""}</div>`;status.textContent="Answer found in the GST knowledge library.";return}status.textContent="No sufficiently relevant topic was found. Try another GST question or a broader topic."}
function renderPopular(){const box=document.getElementById("popularArticles");if(!box)return;const picks=[ARTICLES.find(a=>/what is gst/i.test(a.title)),ARTICLES.find(a=>/input tax credit/i.test(a.title)),ARTICLES.find(a=>/gstr.*3b.*due/i.test(a.title)),ARTICLES.find(a=>/export under gst/i.test(a.title))].filter(Boolean);const list=picks.length?picks:ARTICLES.slice(0,4);box.innerHTML=list.map((a,i)=>`<div class="popular-card"><div class="popular-thumb">${["▤","₹","◷","✈"][i]||"▤"}</div><div class="popular-body"><h3>${esc(a.title)}</h3><p>${esc(a.intro||"").slice(0,120)}</p><a href="/articles/${esc(a.slug)}.html">Read article →</a></div></div>`).join("")}
async function init(){await loadData();renderSections();renderArticles(ARTICLES.slice(0,12));renderQA(QA.slice(0,8));renderPopular();const params=new URLSearchParams(location.search);const q=params.get("q");if(q&&document.getElementById("articleSearch")){document.getElementById("articleSearch").value=q;renderArticles(articleResults(q))}}
