
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
function num(v){return parseFloat(String(v??"").replace(/,/g,""))||0}
function pick(keys,names){return keys.find(k=>names.some(n=>k.toLowerCase().includes(n)))||""}
function loadRows(file,cb){const r=new FileReader();r.onload=e=>{try{const wb=XLSX.read(new Uint8Array(e.target.result),{type:"array"});let rows=[];wb.SheetNames.forEach(sn=>{const x=XLSX.utils.sheet_to_json(wb.Sheets[sn],{defval:""});rows=rows.concat(x)});cb(null,rows)}catch(err){cb(err)}};r.readAsArrayBuffer(file)}
function summary(rows){const keys=Object.keys(rows[0]||{}),tax=pick(keys,["taxable value","taxable"]),ig=pick(keys,["igst","integrated tax"]),cg=pick(keys,["cgst","central tax"]),sg=pick(keys,["sgst","state/ut tax","state tax"]),ce=pick(keys,["cess"]),gstin=pick(keys,["gstin","supplier gstin"]),inv=pick(keys,["invoice number","invoice no","document number","invoice"]),vendor=pick(keys,["trade/legal name","supplier name","vendor name","legal name"]);let t=0,igt=0,cgt=0,sgt=0,cest=0;const vendors=new Set();rows.forEach(r=>{t+=num(r[tax]);igt+=num(r[ig]);cgt+=num(r[cg]);sgt+=num(r[sg]);cest+=num(r[ce]);if(vendor&&r[vendor])vendors.add(String(r[vendor]));});return {keys,tax,ig,cg,sg,ce,gstin,inv,vendor,rows:rows.length,t,igt,cgt,sgt,cest,vendors:vendors.size}}
function outSummary(s){return `<div class="result"><strong>Records:</strong> ${s.rows.toLocaleString()} &nbsp; <strong>Taxable:</strong> ₹${s.t.toLocaleString(undefined,{maximumFractionDigits:2})} &nbsp; <strong>GST:</strong> ₹${(s.igt+s.cgt+s.sgt+s.cest).toLocaleString(undefined,{maximumFractionDigits:2})}<br><span class="muted">IGST ₹${s.igt.toFixed(2)} • CGST ₹${s.cgt.toFixed(2)} • SGST/UTGST ₹${s.sgt.toFixed(2)} • Cess ₹${s.cest.toFixed(2)} • Vendors ${s.vendors}</span></div>`}
function runAnalyzer(){const f=document.getElementById("file").files[0];if(!f)return;loadRows(f,(e,rows)=>{const o=document.getElementById("out");if(e){o.innerHTML='<div class="result">Unable to read file.</div>';return}if(!rows.length){o.innerHTML='<div class="result">No data rows found.</div>';return}o.innerHTML=outSummary(summary(rows));})}
function runDup(){const f=document.getElementById("file").files[0];if(!f)return;loadRows(f,(e,rows)=>{const o=document.getElementById("out");if(e||!rows.length){o.innerHTML='<div class="result">Unable to read data.</div>';return}const s=summary(rows),set=new Set(),dups=[];if(!s.gstin||!s.inv){o.innerHTML='<div class="result">Could not identify GSTIN and invoice number columns. Please use clear column headings.</div>';return}rows.forEach((r,i)=>{const k=(r[s.gstin]||"").toString().trim().toUpperCase()+"|"+(r[s.inv]||"").toString().trim().toUpperCase();if(k!=="|"&&set.has(k))dups.push(i+2);set.add(k)});o.innerHTML=outSummary(s)+`<div class="result"><strong>Potential duplicate rows:</strong> ${dups.length}<br>${dups.slice(0,100).join(", ")}</div>`;})}
function runITC(){const f=document.getElementById("file").files[0];if(!f)return;loadRows(f,(e,rows)=>{const o=document.getElementById("out");if(e||!rows.length){o.innerHTML='<div class="result">Unable to read data.</div>';return}const s=summary(rows);o.innerHTML=outSummary(s)+`<div class="result"><strong>Indicative eligible tax working</strong><br>IGST: ₹${s.igt.toFixed(2)}<br>CGST: ₹${s.cgt.toFixed(2)}<br>SGST/UTGST: ₹${s.sgt.toFixed(2)}<br>Cess: ₹${s.cest.toFixed(2)}<p class="small muted">This is a working summary from uploaded data, not a final filed return position.</p></div>`;})}
function runMismatch(){const fs=document.getElementById("files").files;if(fs.length<2)return;loadRows(fs[0],(e,a)=>{loadRows(fs[1],(e2,b)=>{const o=document.getElementById("out");if(e||e2){o.innerHTML='<div class="result">Unable to read one or both files.</div>';return}const sa=summary(a),sb=summary(b);if(!sa.gstin||!sa.inv||!sb.gstin||!sb.inv){o.innerHTML='<div class="result">Could not identify GSTIN and invoice number columns in both files.</div>';return}const map=new Set(b.map(r=>(r[sb.gstin]||"").toString().trim().toUpperCase()+"|"+(r[sb.inv]||"").toString().trim().toUpperCase()));let match=0,miss=0;a.forEach(r=>{const k=(r[sa.gstin]||"").toString().trim().toUpperCase()+"|"+(r[sa.inv]||"").toString().trim().toUpperCase();if(k!=="|"&&map.has(k))match++;else miss++});o.innerHTML=`<div class="result"><strong>File 1 records:</strong> ${a.length} &nbsp; <strong>Matched by GSTIN + invoice number:</strong> ${match} &nbsp; <strong>Not found:</strong> ${miss}</div><div class="notice">A key match is only a starting point. Taxable value, tax amounts, document type, amendments and eligibility should also be reconciled before claiming credit.</div>`;})})}
function calcInterest(){const tax=num(document.getElementById("tax").value),rate=num(document.getElementById("rate").value)||18,days=num(document.getElementById("days").value),v=tax*rate*days/365;document.getElementById("out").innerHTML=`<div class="result"><strong>Indicative interest:</strong> ₹${v.toFixed(2)}<br><span class="small muted">Formula: tax × annual rate × delay days ÷ 365. Verify the applicable rate, start date, end date and statutory method for the relevant period.</span></div>`}
